<?xml version="1.0" encoding="UTF-8"?>
<Gateway xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cprs.xsd">
  <ClientRegistrationForm>
    <ClientTaxpayerIdNo>${cprs.tinNo}</ClientTaxpayerIdNo>
    <ClientCCN>${cprs.clientCcn}</ClientCCN>
    <SecIdNo>${cprs.secIdNo}</SecIdNo>
    <PezaIdNo>${cprs.pezaIdNo}</PezaIdNo>
    <PrcIdNo>${cprs.prcIdNo}</PrcIdNo>
    <SssIdNo>${cprs.sssIdNo}</SssIdNo>
    <PassportIdNo>${cprs.passportIdNo}</PassportIdNo>
    <DriverLicenseIdNo>${cprs.driverLicenseIdNo}</DriverLicenseIdNo>
    <AABAssignedBanks>
      <AABRefNo>${aabAssignedBank.aabAssignedBankRefNo}</AABRefNo>
    <Picture>${cprs.picture}</Picture>
    <ClientTypeCode>${cprs.clientType}</ClientTypeCode>
    <ClientTypeName>${clientType.name}</ClientTypeName>
    <DateOfEffectivity>${cprs.periodOfEffectivity}</DateOfEffectivity>
    <LastDateofTransaction>${cprs.lastDateOfTransaction}</LastDateofTransaction>
    <Business>
      <NatureOfBusiness>${cprs.natureOfBusiness}</NatureOfBusiness>
      <BusinessEntity>${cprs.businessType}</BusinessEntity>
    </Business>
    <FullName>
      <First>${cprs.firstName}</First>
      <Middle>${cprs.middleName}</Middle>
      <Last>${cprs.lastName}</Last>
    </FullName>
    <BusinessName>${cprs.businessName}</BusinessName>
    <Citizenship>${cprs.citizenship}</Citizenship>
    <Location>
      <Address>${cprs.address}</Address>
      <City>${cprs.city}</City>
      <Country>${cprs.country}</Country>
      <ZIP>${cprs.zipCode}</ZIP>
    </Location>
    <ContactInformation>
      <Telephone>${cprs.Telephone}</Telephone>
      <AlternateTelephone>${cprs.contactInformation.altTelephone}</AlternateTelephone>
      <Mobile>${cprs.mobile}</Mobile>
      <Facsimile>${cprs.fax}</Facsimile>
      <Email>${cprs.email}</Email>
    </ContactInformation>
    <Website>${cprs.website}</Website>
    <CBWType>${cprs.customBondedWarehouseType}</CBWType>
    <Special>
      <WarehouseCode>${cprs.customBondedWarehouse}</WarehouseCode>
      <JO291ReferenceNumber>${cprs.jo291}</JO291ReferenceNumber>
      <CertificateOfAuthority>${cprs.certificateOfAuthority}</CertificateOfAuthority>
      <JO291PeriodOfEffectivity>${cprs.jo291PeriodOfEffectivity}</JO291PeriodOfEffectivity>
      <JO291Capacity>${cprs.underWritingCapacity}</JO291Capacity>
    </Special>
    <Capital>
      <CapitalStockAmount>${cprs.capitalStockAmount}</CapitalStockAmount>
      <PaidUpCapitalAmount>${cprs.paidUpCapitalAmount}</PaidUpCapitalAmount>
    </Capital>
    <VASP>
      <PrimaryCCN>${cprs.vaspPrimaryCcn}</PrimaryCCN>
      <SecondaryCCN>${cprs.vaspSecondaryCcn}</SecondaryCCN>
    </VASP>
    <RelatedCompany>
      <RelCompanyName1>${cprs.relatedCompanyName1}</RelCompanyName1>
      <RelCompanyName2>${cprs.relatedCompanyName2}</RelCompanyName2>
      <RelCompanyName3>${cprs.relatedCompanyName3}</RelCompanyName3>
    </RelatedCompany>
    <PrimaryBroker>
      <TaxpayerIdNo>${cprs.priBrokerTaxpayerIdNo}</TaxpayerIdNo>
      <Code>${cprs.priBrokerCCN}</Code>
    </PrimaryBroker>
    <SecondaryBroker>
      <TaxpayerIdNo>${cprs.secBrokerTaxpayerIdNo}</TaxpayerIdNo>
      <Code>${cprs.secBrokerCCN}</Code>
    </SecondaryBroker>
    <ImporterPlantList>
      <#list cprs.importers as importerPlant>
      <ImporterPlant>
        <Location>
          <Address>${importerPlant.address}</Address>
          <City>${importerPlant.city}</City>
          <Country>${importerPlant.country}</Country>
          <ZIP>${importerPlant.zipCode}</ZIP>
        </Location>
      </ImporterPlant>
      </#list>
    </ImporterPlantList>
    <StockholdersList>
      <#list cprs.majorStockholders as stockholder>
      <Stockholders>
        <Picture>${stockholder.picture}</Picture>
        <Signature>${stockholder.signature}</Signature>
        <Name>
          <First>${stockholder.firstName}</First>
          <Middle>${stockholder.middleName}</Middle>
          <Last>${stockholderlastName}</Last>
        </Name>
        <Citizenship>${stockholder.citizenship}</Citizenship>
        <TaxpayerIdNo>${stockholder.tinNo}</TaxpayerIdNo>
        <Location>
          <Address>${stockholder.address}</Address>
          <City>${stockholder.city}</City>
          <Country/>${stockholder.country}</Country>
          <ZIP>${stockholder.zipCode}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${stockholder.telephone}</Telephone>
          <AlternateTelephone>${stockholder.altTelephone}</AlternateTelephone>
          <Mobile>${stockholder.mobile}</Mobile>
          <Facsimile>${stockholder.fax}</Facsimile>
          <Email>${stockholder.email}</Email>
        </ContactInformation>
      </Stockholders>
      </#list>
    </StockholdersList>
    <PrincipalOfficerList>
      <#list cprs.principalOfficers as principalOfficer>
      <PrincipalOfficer>
        <Picture>${principalOfficer.picture}</Picture>
        <Signature>${principalOfficer.signature}</Signature>
        <Name>
          <First>${principalOfficer.firstName}</First>
          <Middle>${principalOfficer.middleName}</Middle>
          <Last>${principalOfficer.lastName}</Last>
        </Name>
        <TaxpayerIdNo>${principalOfficer.tinNo}</TaxpayerIdNo>
        <Position>${principalOfficer.position}</Position>
        <Location>
          <Address>${principalOfficer.address}</Address>
          <City>${principalOfficer.city}</City>
          <Country>${principalOfficer.country}</Country>
          <ZIP>${principalOfficer.zipCode}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${principalOfficer.telephone}</Telephone>
          <AlternateTelephone>${principalOfficer.altTelephone}</AlternateTelephone>
          <Mobile>${principalOfficer.mobile}</Mobile>
          <Facsimile>${principalOfficer.fax}</Facsimile>
          <Email>${principalOfficer.email}</Email>
        </ContactInformation>
      </PrincipalOfficer>
      </#list>
    </PrincipalOfficerList>
    <EquivRespOfcrList>
      <#list cprs.equivRespOfficers as equivalentResponsibleOfficer>
      <EquivRespOfcr>
        <Picture>${equivalentResponsibleOfficer.picture}</Picture>
        <Signature>${equivalentResponsibleOfficer.signature}</Signature>
        <Name>
          <First>${equivalentResponsibleOfficer.firstName}</First>
          <Middle>${equivalentResponsibleOfficer.middleName}</Middle>
          <Last>${equivalentResponsibleOfficer.lastName}</Last>
        </Name>
        <Position>${equivalentResponsibleOfficer.position}</Position>
        <TaxpayerIdNo>${equivalentResponsibleOfficer.tinNo}</TaxpayerIdNo>
        <AreaOfResponsibility>${equivalentResponsibleOfficer.area}</AreaOfResponsibility>
        <Location>
          <Address>${equivalentResponsibleOfficer.address}</Address>
          <City>${equivalentResponsibleOfficer.city}</City>
          <Country>${equivalentResponsibleOfficer.country}</Country>
          <ZIP>${equivalentResponsibleOfficer.zipCode}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${equivalentResponsibleOfficer.telephone}</Telephone>
          <AlternateTelephone>${equivalentResponsibleOfficer.altTelephone}</AlternateTelephone>
          <Mobile>${equivalentResponsibleOfficer.mobile}</Mobile>
          <Facsimile>${equivalentResponsibleOfficer.fax}</Facsimile>
          <Email>${equivalentResponsibleOfficer.email}</Email>
        </ContactInformation>
      </EquivRespOfcr>
      </#list>
    </EquivRespOfcrList>
    <MajorSupplierList>
      <#list cprs.majorSuppliers as majorSupplier>
      <MajorSupplier>
        <TIN>${majorSupplier.majorSupplierTinNo}</TIN>
        <CompanyName>${majorSupplier.majorSupplierCompany}</CompanyName>
        <Location>
          <Address>${majorSupplier.majorSupplierAddress}</Address>
          <City>${majorSupplier.majorSupplierCity}</City>
          <Country>${majorSupplier.majorSupplierCountry}</Country>
          <ZIP>${majorSupplier.majorSupplierZipCode}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${majorSupplier.majorSupplierTelephone}</Telephone>
          <AlternateTelephone>${majorSupplier.majorSupplierAltTelephone}</AlternateTelephone>
          <Mobile>${majorSupplier.majorSupplierMobile}</Mobile>
          <Facsimile>${majorSupplier.majorSupplierFax}</Facsimile>
          <Email>${majorSupplier.majorSupplierEmail}</Email>
        </ContactInformation>
      </MajorSupplier>
      </#list>
    </MajorSupplierList>
    <MajorClientList>
      <#list cprs.majorClientList as majorClient>
      <MajorClient>
        <Name>${majorClient.company}</Name>
        <ClientType>${majorClient.clientType}</ClientType>
        <Location>
          <Address>${majorClient.address}</Address>
          <City>${majorClient.city}</City>
          <Country>${majorClient.country}</Country>
          <ZIP>${majorClient.zipCode}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${majorClient.telephone}</Telephone>
          <AlternateTelephone>${majorClient.altTelephone}</AlternateTelephone>
          <Mobile>${majorClient.mobile}</Mobile>
          <Facsimile>${majorClient.fax}</Facsimile>
          <Email>${majorClient.email}</Email>
          <Website>${majorClient.website}</Website>
        </ContactInformation>
      </MajorClient>
      </#list>
    </MajorClientList>
    <ImportedCommodities>
      <#list importedCommodities as commodity>
      <Commodity>
        <HSCode>${commodity.hsCode}</HSCode>
        <ItemCode>${commodity.itemCode}</ItemCode>
        <ItemDescription>${commodity.itemDescription}</ItemDescription>
      </Commodity>
      </#list>
    </ImportedCommodities>
  </ClientRegistrationForm>
</Gateway>