<?xml version="1.0" encoding="UTF-8"?>
<Gateway>
  <ClientRegistrationForm>
    <ClientTaxpayerIdNo>${cprs.tinNo}</ClientTaxpayerIdNo>
    <ClientCCN>${cprs.clientCcn!}</ClientCCN>
    <SecIdNo>${cprs.secIdNo!}</SecIdNo>
    <PezaIdNo>${cprs.pezaIdNo!}</PezaIdNo>
    <PrcIdNo>${cprs.prcIdNo!}</PrcIdNo>
    <SssIdNo>${cprs.sssIdNo!}</SssIdNo>
    <PassportIdNo>${cprs.passportIdNo!}</PassportIdNo>
    <DriverLicenseIdNo>${cprs.driverLicenseIdNo!}</DriverLicenseIdNo>
    <AABAssignedBanks>
      <#if aabAssignedBank??>
      <AABRefNo>${aabAssignedBank.aabAssignedBankRefNo!}</AABRefNo>
      </#if>
    </AABAssignedBanks>
    <#if profilePicture??>
    <Picture><![CDATA[${profilePicture}]]></Picture>
    </#if>
    <ClientTypeCode>${cprs.clientType!}</ClientTypeCode>
    <ClientTypeName>${clientType.name!}</ClientTypeName>
    <DateOfEffectivity>${cprs.periodOfEffectivity!}</DateOfEffectivity>
    <LastDateofTransaction>${cprs.lastDateOfTransaction!?date}</LastDateofTransaction>
    <Business>
      <NatureOfBusiness>${cprs.natureOfBusiness!}</NatureOfBusiness>
      <BusinessEntity>${cprs.businessType!}</BusinessEntity>
    </Business>
    <FullName>
      <First>${cprs.firstName!}</First>
      <Middle>${cprs.middleName!}</Middle>
      <Last>${cprs.lastName!}</Last>
    </FullName>
    <BusinessName>${cprs.businessName!}</BusinessName>
    <Citizenship>${cprs.citizenship!}</Citizenship>
    <Location>
      <Address>${cprs.address!}</Address>
      <City>${cprs.city!}</City>
      <Country>${cprs.country!}</Country>
      <ZIP>${cprs.zipCode!}</ZIP>
    </Location>
    <ContactInformation>
      <Telephone>${cprs.Telephone!}</Telephone>
      <AlternateTelephone>${cprs.altTelephone!}</AlternateTelephone>
      <Mobile>${cprs.mobile!}</Mobile>
      <Facsimile>${cprs.fax!}</Facsimile>
      <Email>${cprs.email!}</Email>
    </ContactInformation>
    <Website>${cprs.website!}</Website>
    <CBWType>${cprs.customBondedWarehouseType!}</CBWType>
    <Special>
      <WarehouseCode>${cprs.customBondedWarehouse!}</WarehouseCode>
      <JO291ReferenceNumber>${cprs.jo291!}</JO291ReferenceNumber>
      <CertificateOfAuthority>${cprs.certificateOfAuthority!}</CertificateOfAuthority>
      <JO291PeriodOfEffectivity>${cprs.jo291PeriodOfEffectivity!}</JO291PeriodOfEffectivity>
      <JO291Capacity>${cprs.underWritingCapacity!}</JO291Capacity>
    </Special>
    <Capital>
      <CapitalStockAmount>${cprs.capitalStockAmount!}</CapitalStockAmount>
      <PaidUpCapitalAmount>${cprs.paidUpCapitalAmount!}</PaidUpCapitalAmount>
    </Capital>
    <VASP>
      <PrimaryCCN>${cprs.vaspPrimaryCcn!}</PrimaryCCN>
      <SecondaryCCN>${cprs.vaspSecondaryCcn!}</SecondaryCCN>
    </VASP>
    <RelatedCompany>
      <RelCompanyName1>${cprs.relatedCompanyName1!}</RelCompanyName1>
      <RelCompanyName2>${cprs.relatedCompanyName2!}</RelCompanyName2>
      <RelCompanyName3>${cprs.relatedCompanyName3!}</RelCompanyName3>
    </RelatedCompany>
    <PrimaryBroker>
      <TaxpayerIdNo>${cprs.priBrokerTaxpayerIdNo!}</TaxpayerIdNo>
      <Code>${cprs.priBrokerCCN!}</Code>
    </PrimaryBroker>
    <SecondaryBroker>
      <TaxpayerIdNo>${cprs.secBrokerTaxpayerIdNo!}</TaxpayerIdNo>
      <Code>${cprs.secBrokerCCN!}</Code>
    </SecondaryBroker>
    <ImporterPlantList>
      <#if cprs.importers??>
      <#list cprs.importers as importerPlant>
      <ImporterPlant>
        <Location>
          <Address>${importerPlant.address!}</Address>
          <City>${importerPlant.city!}</City>
          <Country>${importerPlant.country!}</Country>
          <ZIP>${importerPlant.zipCode!}</ZIP>
        </Location>
      </ImporterPlant>
      </#list>
      </#if>
    </ImporterPlantList>
    <StockholdersList>
      <#if cprs.majorStockholders??>
      <#list cprs.majorStockholders as stockholder>
      <Stockholders>
        <#if stockholder.picture??>
          <Picture><#list stockholderPicture as spic>${spic}</#list></Picture>
        </#if>
        <#if stockholder.signature??>
          <Signature>${stockholderSignature[cprs.majorStockholders?seq_index_of(stockholder)]}</Signature>
        </#if>
        <Name>
          <First>${stockholder.firstName!}</First>
          <Middle>${stockholder.middleName!}</Middle>
          <Last>${stockholderlastName!}</Last>
        </Name>
        <Citizenship>${stockholder.citizenship!}</Citizenship>
        <TaxpayerIdNo>${stockholder.tinNo!}</TaxpayerIdNo>
        <Location>
          <Address>${stockholder.address!}</Address>
          <City>${stockholder.city!}</City>
          <Country/>${stockholder.country!}</Country>
          <ZIP>${stockholder.zipCode!}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${stockholder.telephone!}</Telephone>
          <AlternateTelephone>${stockholder.altTelephone!}</AlternateTelephone>
          <Mobile>${stockholder.mobile!}</Mobile>
          <Facsimile>${stockholder.fax!}</Facsimile>
          <Email>${stockholder.email!}</Email>
        </ContactInformation>
      </Stockholders>
      </#list>
      </#if>
    </StockholdersList>
    <PrincipalOfficerList>
      <#if cprs.principalOfficers??>
      <#list cprs.principalOfficers as principalOfficer>
      <PrincipalOfficer>
        <#if principalOfficer.picture??>
          <Picture>${picture[cprs.principalOfficers?seq_index_of(principalOfficer)]}</Picture>
        </#if>
        <#if principalOfficer.signature??>
          <Signature>${signature[cprs.principalOfficers?seq_index_of(principalOfficer)]}</Signature>
        </#if>
        <Name>
          <First>${principalOfficer.firstName!}</First>
          <Middle>${principalOfficer.middleName!}</Middle>
          <Last>${principalOfficer.lastName!}</Last>
        </Name>
        <TaxpayerIdNo>${principalOfficer.tinNo!}</TaxpayerIdNo>
        <Position>${principalOfficer.position!}</Position>
        <Location>
          <Address>${principalOfficer.address!}</Address>
          <City>${principalOfficer.city!}</City>
          <Country>${principalOfficer.country!}</Country>
          <ZIP>${principalOfficer.zipCode!}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${principalOfficer.telephone!}</Telephone>
          <AlternateTelephone>${principalOfficer.altTelephone!}</AlternateTelephone>
          <Mobile>${principalOfficer.mobile!}</Mobile>
          <Facsimile>${principalOfficer.fax!}</Facsimile>
          <Email>${principalOfficer.email!}</Email>
        </ContactInformation>
      </PrincipalOfficer>
      </#list>
      </#if>
    </PrincipalOfficerList>
    <EquivRespOfcrList>
      <#if cprs.equivRespOfficers??>
      <#list cprs.equivRespOfficers as equivalentResponsibleOfficer>
      <EquivRespOfcr>
        <#if equivalentResponsibleOfficer.picture??>
          <Picture>${picture[cprs.equivRespOfficers?seq_index_of(equivalentResponsibleOfficer)]}</Picture>
        </#if>
        <#if equivalentResponsibleOfficer.signature??>
          <Signature>${signature[cprs.equivRespOfficers?seq_index_of(equivalentResponsibleOfficer)]}</Signature>
        </#if>
        <Name>
          <First>${equivalentResponsibleOfficer.firstName!}</First>
          <Middle>${equivalentResponsibleOfficer.middleName!}</Middle>
          <Last>${equivalentResponsibleOfficer.lastName!}</Last>
        </Name>
        <Position>${equivalentResponsibleOfficer.position!}</Position>
        <TaxpayerIdNo>${equivalentResponsibleOfficer.tinNo!}</TaxpayerIdNo>
        <AreaOfResponsibility>${equivalentResponsibleOfficer.area!}</AreaOfResponsibility>
        <Location>
          <Address>${equivalentResponsibleOfficer.address!}</Address>
          <City>${equivalentResponsibleOfficer.city!}</City>
          <Country>${equivalentResponsibleOfficer.country!}</Country>
          <ZIP>${equivalentResponsibleOfficer.zipCode!}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${equivalentResponsibleOfficer.telephone!}</Telephone>
          <AlternateTelephone>${equivalentResponsibleOfficer.altTelephone!}</AlternateTelephone>
          <Mobile>${equivalentResponsibleOfficer.mobile!}</Mobile>
          <Facsimile>${equivalentResponsibleOfficer.fax!}</Facsimile>
          <Email>${equivalentResponsibleOfficer.email!}</Email>
        </ContactInformation>
      </EquivRespOfcr>
      </#list>
      </#if>
    </EquivRespOfcrList>
    <MajorSupplierList>
      <#if cprs.majorSuppliers??>
      <#list cprs.majorSuppliers as majorSupplier>
      <MajorSupplier>
        <TIN>${majorSupplier.majorSupplierTinNo!}</TIN>
        <CompanyName>${majorSupplier.majorSupplierCompany!}</CompanyName>
        <Location>
          <Address>${majorSupplier.majorSupplierAddress!}</Address>
          <City>${majorSupplier.majorSupplierCity!}</City>
          <Country>${majorSupplier.majorSupplierCountry!}</Country>
          <ZIP>${majorSupplier.majorSupplierZipCode!}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${majorSupplier.majorSupplierTelephone!}</Telephone>
          <AlternateTelephone>${majorSupplier.majorSupplierAltTelephone!}</AlternateTelephone>
          <Mobile>${majorSupplier.majorSupplierMobile!}</Mobile>
          <Facsimile>${majorSupplier.majorSupplierFax!}</Facsimile>
          <Email>${majorSupplier.majorSupplierEmail!}</Email>
        </ContactInformation>
      </MajorSupplier>
      </#list>
      </#if>
    </MajorSupplierList>
    <MajorClientList>
      <#if cprs.majorClients??>
      <#list cprs.majorClients as majorClient>
      <MajorClient>
        <Name>${majorClient.company!}</Name>
        <ClientType>${majorClient.clientType!}</ClientType>
        <Location>
          <Address>${majorClient.address!}</Address>
          <City>${majorClient.city!}</City>
          <Country>${majorClient.country!}</Country>
          <ZIP>${majorClient.zipCode!}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${majorClient.telephone!}</Telephone>
          <AlternateTelephone>${majorClient.altTelephone!}</AlternateTelephone>
          <Mobile>${majorClient.mobile!}</Mobile>
          <Facsimile>${majorClient.fax!}</Facsimile>
          <Email>${majorClient.email!}</Email>
          <Website>${majorClient.website!}</Website>
        </ContactInformation>
      </MajorClient>
      </#list>
      </#if>
    </MajorClientList>
    <ImportedCommodities>
      <#if importedCommodities??>
      <#list importedCommodities as commodity>
      <Commodity>
        <HSCode>${commodity.hsCode!}</HSCode>
        <ItemCode>${commodity.itemCode!}</ItemCode>
        <ItemDescription>${commodity.itemDescription!}</ItemDescription>
      </Commodity>
      </#list>
      </#if>
    </ImportedCommodities>    
  </ClientRegistrationForm>
</Gateway>