<?xml version="1.0" encoding="UTF-8"?>
<Gateway xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cprs.xsd">
  <ClientRegistrationForm>
    <ClientTaxpayerIdNo>${cprs.clientTaxpayerIdNo}</ClientTaxpayerIdNo>
    <ClientCCN>${cprs.clientCCN}</ClientCCN>
    <SecIdNo>${cprs.secIdNo}</SecIdNo>
    <PezaIdNo>${cprs.pezaIdNo}</PezaIdNo>
    <PrcIdNo>${cprs.prcIdNo}</PrcIdNo>
    <SssIdNo>${cprs.sssIdNo}</SssIdNo>
    <PassportIdNo>${cprs.passportIdNo}</PassportIdNo>
    <DriverLicenseIdNo>${cprs.driverLicenseIdNo}</DriverLicenseIdNo>
    <AABAssignedBanks>
    <#list cprs.aabAssignedBanks as aabAssignedBank>
      <AABRefNo>${aabAssignedBank.aabRefNo}</AABRefNo>
	</#list>
    <Picture>${cprs.picture}</Picture>
    <ClientTypeCode>${cprs.clientTypeCode}</ClientTypeCode>
    <ClientTypeName>${cprs.clientTypeName}</ClientTypeName>
    <DateOfEffectivity>${cprs.dateOfEffectivity}</DateOfEffectivity>
    <LastDateofTransaction>${cprs.lastDateofTransaction}</LastDateofTransaction>
    <Business>
      <NatureOfBusiness>${cprs.business.natureOfBusiness}</NatureOfBusiness>
      <BusinessEntity>${cprs.business.businessEntity}</BusinessEntity>
    </Business>
    <FullName>
      <First>${cprs.name.first}</First>
      <Middle>${cprs.name.middle}</Middle>
      <Last>${cprs.name.last}</Last>
    </FullName>
    <BusinessName>${cprs.businessName}</BusinessName>
    <Citizenship>${cprs.citizenship}</Citizenship>
    <Location>
      <Address>${cprs.location.address}</Address>
      <City>${cprs.location.city}</City>
      <Country>${cprs.location.country}</Country>
      <ZIP>${cprs.location.zip}</ZIP>
    </Location>
    <ContactInformation>
      <Telephone>${cprs.contactInformation.telephone}</Telephone>
      <AlternateTelephone>${cprs.contactInformation.alternateTelephone}</AlternateTelephone>
      <Mobile>${cprs.contactInformation.mobile}</Mobile>
      <Facsimile>${cprs.contactInformation.facsimile}</Facsimile>
      <Email>${cprs.contactInformation.email}</Email>
    </ContactInformation>
    <Website>${cprs.website}</Website>
    <CBWType>${cprs.priv}</CBWType>
    <Special>
      <WarehouseCode>${cprs.special.warehouseCode}</WarehouseCode>
      <JO291ReferenceNumber>${cprs.special.jo291ReferenceNumber}</JO291ReferenceNumber>
      <CertificateOfAuthority>${cprs.special.certificateOfAuthority}</CertificateOfAuthority>
      <JO291PeriodOfEffectivity>${cprs.special.jo291PeriodOfEffectivity}</JO291PeriodOfEffectivity>
      <JO291Capacity>${cprs.special.jo291Capacity}</JO291Capacity>
    </Special>
    <Capital>
      <CapitalStockAmount>${cprs.capital.capitalStockAmount}</CapitalStockAmount>
      <PaidUpCapitalAmount>${cprs.capital.paidUpCapitalAmount}</PaidUpCapitalAmount>
    </Capital>
    <VASP>
      <PrimaryCCN>${cprs.vasp.primaryCCN}</PrimaryCCN>
      <SecondaryCCN>${cprs.vasp.secondaryCCN}</SecondaryCCN>
    </VASP>
    <RelatedCompany>
      <RelCompanyName1>${cprs.relatedCompany.relCompanyName1}</RelCompanyName1>
      <RelCompanyName2>${cprs.relatedCompany.relCompanyName2}</RelCompanyName2>
      <RelCompanyName3>${cprs.relatedCompany.relCompanyName3}</RelCompanyName3>
    </RelatedCompany>
    <PrimaryBroker>
      <TaxpayerIdNo>${cprs.primaryBroker.taxpayerIdNo}</TaxpayerIdNo>
      <Code>${cprs.primaryBroker.code}</Code>
    </PrimaryBroker>
    <SecondaryBroker>
      <TaxpayerIdNo>${cprs.secondaryBroker.TaxpayerIdNo}</TaxpayerIdNo>
      <Code>${cprs.secondaryBroker.code}</Code>
    </SecondaryBroker>
    <ImporterPlantList>
      <#list cprs.importerPlantList as importerPlant>
      <ImporterPlant>
        <Location>
          <Address>${importerPlant.location.address}</Address>
          <City>${importerPlant.location.city}</City>
          <Country>${importerPlant.location.country}</Country>
          <ZIP>${importerPlant.location.zip}</ZIP>
        </Location>
      </ImporterPlant>
      </#list>
    </ImporterPlantList>
    <StockholdersList>
      <#list cprs.stockholderList as stockholder>
      <Stockholders>
        <Picture>${stockholder.picture}</Picture>
        <Signature>${stockholder.signature}</Signature>
        <Name>
          <First>${stockholder.name.first}</First>
          <Middle>${stockholder.name.middle}</Middle>
          <Last>${stockholder.name.last}</Last>
        </Name>
        <Citizenship>${stockholder.citizenship}</Citizenship>
        <TaxpayerIdNo>${stockholder.taxpayerIdNo}</TaxpayerIdNo>
        <Location>
          <Address>${stockholder.location.address}</Address>
          <City>${stockholder.location.city}</City>
          <Country/>${stockholder.location.country}</Country>
          <ZIP>${stockholder.location.zip}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${stockholder.contactInformation.telephone}</Telephone>
          <AlternateTelephone>${stockholder.contactInformation.alternateTelephone}</AlternateTelephone>
          <Mobile>${stockholder.contactInformation.mobile}</Mobile>
          <Facsimile>${stockholder.contactInformation.facsimile}</Facsimile>
          <Email>${stockholder.contactInformation.email}</Email>
        </ContactInformation>
      </Stockholders>
      </#list>
    </StockholdersList>
    <PrincipalOfficerList>
      <#list cprs.principalOfficer as principalOfficer>
      <PrincipalOfficer>
        <Picture>${principalOfficer.picture}</Picture>
        <Signature>${principalOfficer.signature}</Signature>
        <Name>
          <First>${principalOfficer.name.first}</First>
          <Middle>${principalOfficer.name.middle}</Middle>
          <Last>${principalOfficer.name.last}</Last>
        </Name>
        <TaxpayerIdNo>${principalOfficer.taxpayerIdNo}</TaxpayerIdNo>
        <Position>${principalOfficer.position}</Position>
        <Location>
          <Address>${principalOfficer.location.address}</Address>
          <City>${principalOfficer.location.city}</City>
          <Country>${principalOfficer.location.country}</Country>
          <ZIP>${principalOfficer.location.zip}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${principalOfficer.contactInformation.telephone}</Telephone>
          <AlternateTelephone>${principalOfficer.contactInformation.alternateTelephone}</AlternateTelephone>
          <Mobile>${principalOfficer.contactInformation.mobile}</Mobile>
          <Facsimile>${principalOfficer.contactInformation.facsimile}</Facsimile>
          <Email>${principalOfficer.contactInformation.email}</Email>
        </ContactInformation>
      </PrincipalOfficer>
      </#list>
    </PrincipalOfficerList>
    <EquivRespOfcrList>
      <#list cprs.equivalentResponsibleOfficerList as equivalentResponsibleOfficer>
      <EquivRespOfcr>
        <Picture>${equivalentResponsibleOfficer.picture}</Picture>
        <Signature>${equivalentResponsibleOfficer.signature}</Signature>
        <Name>
          <First>${equivalentResponsibleOfficer.name.first}</First>
          <Middle>${equivalentResponsibleOfficer.name.middle}</Middle>
          <Last>${equivalentResponsibleOfficer.name.last}</Last>
        </Name>
        <Position>${equivalentResponsibleOfficer.position}</Position>
        <TaxpayerIdNo>${equivalentResponsibleOfficer.taxpayerIdNo}</TaxpayerIdNo>
        <AreaOfResponsibility>${equivalentResponsibleOfficer.areaOfResponsibility}</AreaOfResponsibility>
        <Location>
          <Address>${equivalentResponsibleOfficer.location.address}</Address>
          <City>${equivalentResponsibleOfficer.location.city}</City>
          <Country>${equivalentResponsibleOfficer.location.country}</Country>
          <ZIP>${equivalentResponsibleOfficer.location.zip}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${equivalentResponsibleOfficer.contactInformation.telephone}</Telephone>
          <AlternateTelephone>${equivalentResponsibleOfficer.contactInformation.alternateTelephone}</AlternateTelephone>
          <Mobile>${equivalentResponsibleOfficer.contactInformation.mobile}</Mobile>
          <Facsimile>${equivalentResponsibleOfficer.contactInformation.facsimile}</Facsimile>
          <Email>${equivalentResponsibleOfficer.contactInformation.email}</Email>
        </ContactInformation>
      </EquivRespOfcr>
      </#list>
    </EquivRespOfcrList>
    <MajorSupplierList>
      <#list cprs.majorSupplierList as majorSupplier>
      <MajorSupplier>
        <TIN>${majorSupplier.taxpayerIdNo}</TIN>
        <CompanyName>${majorSupplier.companyName}</CompanyName>
        <Location>
          <Address>${majorSupplier.location.address}</Address>
          <City>${majorSupplier.location.city}</City>
          <Country>${majorSupplier.location.country}</Country>
          <ZIP>${majorSupplier.location.zip}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${majorSupplier.contactInformation.telephone}</Telephone>
          <AlternateTelephone>${majorSupplier.contactInformation.alternateTelephone}</AlternateTelephone>
          <Mobile>${majorSupplier.contactInformation.mobile}</Mobile>
          <Facsimile>${majorSupplier.contactInformation.facsimile}</Facsimile>
          <Email>${majorSupplier.contactInformation.email}</Email>
        </ContactInformation>
      </MajorSupplier>
      </#list>
    </MajorSupplierList>
    <MajorClientList>
      <#list cprs.majorClientList as majorClient>
      <MajorClient>
        <Name>${majorClient.name}</Name>
        <ClientType>${majorClient.clientType}</ClientType>
        <Location>
          <Address>${majorClient.location.address}</Address>
          <City>${majorClient.location.city}</City>
          <Country>${majorClient.location.country}</Country>
          <ZIP>${majorClient.location.zip}</ZIP>
        </Location>
        <ContactInformation>
          <Telephone>${majorClient.contactInformation.telephone}</Telephone>
          <AlternateTelephone>${majorClient.contactInformation.alternateTelephone}</AlternateTelephone>
          <Mobile>${majorClient.contactInformation.mobile}</Mobile>
          <Facsimile>${majorClient.contactInformation.facsimile}</Facsimile>
          <Email>${majorClient.contactInformation.email}</Email>
          <Website>${majorClient.website}</Website>
        </ContactInformation>
      </MajorClient>
      </#list>
    </MajorClientList>
    <ImportedCommodities>
      <#list cprs.importedCommodities as commodity>
      <Commodity>
        <HSCode>${commodity.hsCode}</HSCode>
        <ItemCode>${commodity.itemCode}</ItemCode>
        <ItemDescription>${commodity.itemDescription}</ItemDescription>
      </Commodity>
      </#list>
    </ImportedCommodities>
  </ClientRegistrationForm>
</Gateway>