[
<#if (clientType == "IM")>
["Government Services Jo 2-91","GO004"],
</#if>
["Accounting, Bookkeeping, Auditing Activities","7412"],
["Activities Auxiliary To Financial Intermediation, N.E.C.","6819"],
["Activities Auxiliary To Insurance and Pension Funding","6820"],
["Activities of Booking Offices","6352"],
["Activities of Business, Employers Organizations","9111"],
["Activities of Other Membership Organizations, N.E.C","9199"],
["Activities of Other Transport Agencies N.E.C","6399"],
["Activities of Political Organizations","9192"],
["Activities of Professional Organizations","9112"],
["Activities of Religious Organizations","9191"],
["Activities of Tour and Travel Agencies","6351"],
["Activities of Trade Unions","9120"],
["Adminstration of Financial Markets","6811"],
["Advertising","7430"],
["Agricultural, Animal Husbandry Service Activities","0390"],
["Ancillary Service Activities For The Government","7514"],
["Apiary (Bee Culture For The Production of Honey)","0292"],
["Architectural, Engineering Activities, Technical Consultancy","7421"],
["Art Galleries","9234"],
["Artificial Insemination Services","0371"],
["Baking of Dry Bakery Products","1562"],
["Baking of Perishable Bakery Products","1561"],
["Banking Activities N.E.C","6599"],
["Bars and Cocktail Lounges","5524"],
["Beef Cattle Farming (Including Feed Lot Fattening)","0221"],
["Botanical, Zoological Gardens, Nature Reserves Activities","9233"],
["Building and Repairing of Pleasure, Sporting Boats","3512"],
["Building and Repairing of Ships","3511"],
["Building-Cleaning Activities","7493"],
["Building Components Installation Contractors","4532"],
["Building Installations N.E.C","4539"],
["Building of Constructions Or Parts, Civil Engineering","4520"],
["Business and Management Consultancy Activities","7414"],
["Bus Line Operation","6011"],
["Buying, Selling, Renting, Leasing, Operation of Dwellings","7011"],
["Carabao Farming","0222"],
["Cargo Handling","6311"],
["Carpentry","4544"],
["Catching and Culturing Ornamental (Aquarium) Fishes","0692"],
["Catching Fish, Crabs and Crustaceans In Inland Waters","0621"],
["Cemetery Development, Sale","7013"],
["Central Banking","6510"],
["Chartered Buses and Cars Operation","6094"],
["Chemical, Fertilizer Mineral Mining: Baryte, Guano, Pyrite","1191"],
["Chemical, Mechanical Weed, Disease, Pest Control Services","0333"],
["Chicken Broiler Production (Operation of Chicken Hatcheries)","0230"],
["Chicken Egg Production","0251"],
["Chromite Ore Mining","1030"],
["Clay Quarrying","1134"],
["Coal Mining","1110"],
["Coastal Fishing, Municipal (W/ Vessels Less Than 3 Tons)","0612"],
["Coffee Roasting and Processing","1595"],
["Cold Storage","6344"],
["Collection, Purification, Distribution of Water","4100"],
["Compulsory Social Security Activities","7530"],
["Contract Animal Growing Services On A Fee Basis","0372"],
["Copper Ore Mining","1020"],
["Cotton Ginning","0360"],
["Courier Activities Other Than National Postal Activities","6412"],
["Crocodile/Alligator Farming","0296"],
["Curing and Redrying Tobacco Leaves","1604"],
["Custom Dressmaking","1822"],
["Customs Bonded Warehouses","6342"],
["Customs Brokerage (Ship and Aircraft)","6391"],
["Custom Tailoring","1821"],
["Cutting, Shaping and Finishing of Stone","2696"],
["Dairy Farming: Dairy Products Processed In The Farm","0260"],
["Data Base Activities","7250"],
["Data Processing - Data Conversion Services","7240"],
["Day and Night Clubs","5523"],
["Defense Activities","7522"],
["Distilling, Rectifying, Blending of Spirits","1551"],
["Dormitories/ Boarding Houses","5512"],
["Dramatic Arts, Music, Other Arts Activities","9214"],
["Duck Broiler Farming","0241"],
["Duck Egg Production","0252"],
["Egg-Hatching, Sex Determination, Other Poultry Services","0373"],
["Egg Production, N.E.C.","0259"],
["Electrical and Mechanical Work At Site of Construction","4533"],
["Expanded Commercial Banking (Universal Banking)","6591"],
["Extraction of Salt","1194"],
["Extraction, Production of Crude Petroleum, Natural Gas","1120"],
["Extra-Territorial Organizations and Bodies","9900"],
["Farm Management Services","0380"],
["Fertilizer Application","0332"],
["Financial Holding Company Activities","6694"],
["Financial Leasing","6697"],
["Financing Company Operations","6611"],
["Finishing of Textiles","1712"],
["Fish Corral Fishing","0613"],
["Fishpen and Fishcage Operation","0642"],
["Fishpond Operation (Except Fish Breeding Farms, Nurseries)","0641"],
["Floor and Wall Tiling Or Covering With Other Material","4542"],
["Foreign Affairs","7521"],
["Foreign Exchange Dealing","6813"],
["Forging, Pressing, Stamping, Roll-Forming of Metal","2891"],
["Freight Forwarding Services","6392"],
["Frog Farming","0294"],
["Funeral and Related Activities","9303"],
["Game Fowl Farming","0245"],
["Game Propagation, Breeding Activities","0430"],
["Gathering Fry","0693"],
["Gathering of Laver and Other Edible Seaweeds","0691"],
["Gathering Shells and Clams, Edible, In Inland Waters","0622"],
["General Bonded Warehouses Except Grain Warehouses","6341"],
["General (Overall) Public Service Activities","7511"],
["Generation, Collection and Distribution of Electricity","4010"],
["Goat Farming","0225"],
["Gold and Other Precious Metal Refining","2721"],
["Gold Ore Mining","1010"],
["Grain Warehouses","6343"],
["Growing of Abaca","0191"],
["Growing of Banana","0140"],
["Growing of Banana, Cavendish","0141"],
["Growing of Cacao","0182"],
["Growing of Citrus: Calamansi, Orange, Pomelo","0163"],
["Growing of Coconut, Copra, Tuba, Coco-Shell Charcoal Making","0130"],
["Growing of Coffee","0181"],
["Growing of Corn, Except Young Corn (Vegetable)","0120"],
["Growing of Edible Nuts, Except Groundnut (Peanut)","0165"],
["Growing of Fiber Crops (Except Abaca), Cotton","0192"],
["Growing of Fruit-, Flower-Bearing Vegetable: Tomato","0172"],
["Growing of Fruits (Except Banana), Nuts","0160"],
["Growing of Groundnut (Peanut)","0164"],
["Growing of Horticultural Specialties, Nursery Products","0178"],
["Growing of Leafy and Stem Vegetable","0173"],
["Growing of Mango","0162"],
["Growing of Mongo","0174"],
["Growing of Other Banana","0149"],
["Growing of Other Crops: Oil Producing Crops, Forage Crops","0199"],
["Growing of Other Fruits: Grapes, Other Fruits N.E.C","0169"],
["Growing of Palay (Irrigated, Rained, Upland)","0110"],
["Growing of Palay, Lowland Irrigated","0111"],
["Growing of Palay, Lowland Rained","0112"],
["Growing of Palay, Upland/Kaingin","0113"],
["Growing of Peas, Beans, Other Leguminous Vegetables","0176"],
["Growing of Pineapple","0161"],
["Growing of Root and Tuber Crops: Cassava, Potato","0177"],
["Growing of Root, Bulb, Tuberous Vegetables","0171"],
["Growing of Rubber Tree","0194"],
["Growing of Soya Bean","0175"],
["Growing of Spice, Condiment Crops","0184"],
["Growing of Sugarcane, Muscovado, Sugar-Making In The Farm","0150"],
["Growing of Tea, Other Beverage Crops","0183"],
["Growing of Timber, Planting, Thinning of Timber Tracts","0502"],
["Growing of Tobacco, Including Its Preliminar Processing","0193"],
["Hairdressing and Other Beauty Treatment","9302"],
["Hardware Consultancy","7210"],
["Harvesting, Threshing, Grading, Bailing Services","0340"],
["Hog Farming","0210"],
["Horse/Stud Farming","0223"],
["Hotels and Motels","5511"],
["Hunting, Trapping, Other Related Services N.E.C.","0490"],
["Hunting, Trapping Wild Animals In The Forest","0410"],
["Inland Fishing N.E.C","0629"],
["Inland Water Transport","6120"],
["Interior Decoration","4543"],
["Investigation, Security Activities","7492"],
["Investment Company Operation","6691"],
["Investment House Operation","6692"],
["Iron and Steel Casting/Foundry","2731"],
["Iron Ore Mining","1091"],
["Jeepney and Asian Utility Vehicle (Auv) Operation","6092"],
["Labor Recruitment, Provision of Personnel","7491"],
["Legal Activities","7411"],
["Lending Investor Activities","6612"],
["Library and Archives Activities","9231"],
["Life Insurance","6701"],
["Limestone Quarrying","1132"],
["Livestock Farming (Including Feed Lot Services), N.E.C","0229"],
["Logging Operations","0501"],
["Maintenance and Repair of Motor Vehicles","5020"],
["Maintenance, Repair of Office, Acctg, Computing Machinery","7260"],
["Management/Administrative Services","7496"],
["Manganese Ore Mining","1092"],
["Manufacture and Repair of Furniture and Fixtures of Metal","3606"],
["Manufacture and Repair of Other Furniture and Fixtures","3609"],
["Manufacture and Repair of Rattan Furniture","3602"],
["Manufacture and Repair of Wood Furniture","3601"],
["Manufacture of Accumulators, Primary Cells, Batteries","3140"],
["Manufacture of Agricultural and Forestry Machinery","2921"],
["Manufacture of Aircraft and Spacecraft","3530"],
["Manufacture of Articles For Personal Use","3994"],
["Manufacture of Articles of Concrete, Cement, Plaster","2695"],
["Manufacture of Articles of Cork, Straw, Plaiting Materials","2022"],
["Manufacture of Artificial Flowers, Fruits and Foliage","3997"],
["Manufacture of Baby Carriages","3992"],
["Manufacture of Basic Chemicals Not Fertilizers","2411"],
["Manufacture of Basic Precious and Non-Ferrous Metal","2729"],
["Manufacture of Bearings, Gears, Gearing, Driving Elements","2913"],
["Manufacture of Bicycles and Invalid Carriages","3592"],
["Manufacture of Billiard, Pool, Bowling Alley Equipment","3943"],
["Manufacture of Bodies For Motor Vehicles, Trailers","3420"],
["Manufacture of Box Beds and Mattresses","3603"],
["Manufacture of Builder's Carpentry, Joinery, Millworking","2013"],
["Manufacture of Butter and Cheese","1524"],
["Manufacture of Candles","3996"],
["Manufacture of Carpets and Rugs","1722"],
["Manufacture of Cement","2620"],
["Manufacture of Chewing and Smoking Tobacco, Snuff","1603"],
["Manufacture of Cigarettes","1601"],
["Manufacture of Cigars","1602"],
["Manufacture of Cocoa, Chocolate, Sugar Confectionery","1591"],
["Manufacture of Coke Oven Products","2310"],
["Manufacture of Containers, Boxes of Paper, Paperboard","2102"],
["Manufacture of Cordate, Rope, Twine and Netting","1723"],
["Manufacture of Cutlery, Hand Tools, General Hardware","2893"],
["Manufacture of Dairy Products N.E.C","1529"],
["Manufacture of Dessicated Coconut","1593"],
["Manufacture of Dolls and Doll Garments","3941"],
["Manufacture of Domestic Appliances, N.E.C","2930"],
["Manufacture of Electric Games (Video Games, Checkers)","3944"],
["Manufacture of Electricity Distribution, Control Apparatus","3120"],
["Manufacture of Electric Motors, Generators, Transformers","3110"],
["Manufacture of Electronic Valves, Tubes","3210"],
["Manufacture of Embroidered Fabrics","1740"],
["Manufacture of Engines, Turbines, Not Aircraft/Cycle Engines","2911"],
["Manufacture of Fertilizers and Nitrogen Compounds","2421"],
["Manufacture of Footwear, N.E.C","1929"],
["Manufacture of Gas, Distribution of Gaseous Fuels Via Mains","4020"],
["Manufacture of Glass and Glass Products","2610"],
["Manufacture of Grain, Vegetable Mill Products Not Rice/Corn","1543"],
["Manufacture of Guitars","3922"],
["Manufacture of Hats, Gloves, Handkerchiefs, Neckwear, Belts","1892"],
["Manufacture of Ice Cream Cones and Wafers","1563"],
["Manufacture of Ice Cream, Sherbet, Ice Drop, Ice Candy","1525"],
["Manufacture of Ice, Except Dry Ice","1596"],
["Manufacture of Imitation Jewelry","3998"],
["Manufacture of Industrial Process Control Equipment","3313"],
["Manufacture of Infants' Powdered Milk","1523"],
["Manufacture of Insulated Wire and Cables","3130"],
["Manufacture of Jewelry","3911"],
["Manufacture of Jewelry and Related Articles, N.E.C","3919"],
["Manufacture of Knitted and Crocheted Articles, N.E.C","1739"],
["Manufacture of Knitted and Crocheted Fabrics","1731"],
["Manufacture of Knitted or Crocheted Undergarments","1732"],
["Manufacture of Leather Shoes","1921"],
["Manufacture of Lifting and Handling Equipment","2915"],
["Manufacture of Lighting Equipment, Electric Lamps","3150"],
["Manufacture of Lime and Plaster","2694"],
["Manufacture of Linoleum and Hard Surface Floor Coverings","3995"],
["Manufacture of Macaroni, Noodles, Farinaceous Products","1592"],
["Manufacture of Machinery: Food, Beverage, Tobacco Processing","2925"],
["Manufacture of Machinery: Metallurgy","2923"],
["Manufacture of Machinery: Mining, Quarrying, Construction","2924"],
["Manufacture of Machinery: Textile Apparel, Leather Prod'n","2926"],
["Manufacture of Machine-Tools","2922"],
["Manufacture of Made-Up Textile Articles, Not Wearing Apparel","1721"],
["Manufacture of Malt Liquors and Malt","1553"],
["Manufacture of Man-Made Filament Tow Or Staple Fibers","2432"],
["Manufacture of Measuring, Navigating Instruments","3312"],
["Manufacture of Medical, Surgical Equipment","3311"],
["Manufacture of Medicinal Chemicals, Botanical Products","2424"],
["Manufacture of Milk-Based Infants' and Dietetic Foods","1526"],
["Manufacture of Milk (Powdered, Condensed, Evaporated)","1522"],
["Manufacture of Motorcycles","3591"],
["Manufacture of Motor Vehicles","3410"],
["Manufacture of Muscovado Sugar Not In The Farm","1573"],
["Manufacture of Musical Instruments, N.E.C","3929"],
["Manufacture of Musical Organs (All Types)","3925"],
["Manufacture of Nata De Coco","1594"],
["Manufacture of Non-Structural Non-Refractory Ceramicware","2691"],
["Manufacture of Office, Accounting, Computing Machinery","3000"],
["Manufacture of Optical Instruments, Photographic Equipment","3320"],
["Manufacture of Other Articles, N.E.C","3999"],
["Manufacture of Other Articles of Paper and Paperboard","2109"],
["Manufacture of Other Chemical Products, N.E.C","2429"],
["Manufacture of Other Electrical Equipment, N.E.C","3190"],
["Manufacture of Other Fabricated Metal Products","2899"],
["Manufacture of Other Food Products, N.E.C","1599"],
["Manufacture of Other Fuel Products","2390"],
["Manufacture of Other General Purpose Machinery","2919"],
["Manufacture of Other Non-Metallic Mineral Products","2699"],
["Manufacture of Other Rubber Products","2519"],
["Manufacture of Other Special Purpose Machinery","2929"],
["Manufacture of Other Textiles, N.E.C","1729"],
["Manufacture of Other Transport Equipment, N.E.C","3599"],
["Manufacture of Other Wearing Apparel N.E.C","1899"],
["Manufacture of Ovens, Furnaces, Furnace Burners","2914"],
["Manufacture of Paints, Varnishes, Coatings, Ink, Mastics","2423"],
["Manufacture of Partitions, Shelves, Lockers, Office Fixtures","3604"],
["Manufacture of Parts, Accessories For Motor Vehicles","3430"],
["Manufacture of Pens, Pencils of All Kinds","3991"],
["Manufacture of Pesticides, Other Agro-Chemical Products","2422"],
["Manufacture of Pianos","3921"],
["Manufacture of Pipe Fittings of Non-Ferrous Metal","2724"],
["Manufacture of Plastic Furniture","3605"],
["Manufacture of Plastic Products","2520"],
["Manufacture of Plastic Shoes","1923"],
["Manufacture of Plastics In Primary Forms, Synthetic Rubber","2412"],
["Manufacture of Products of Leather and Imitation Leather","1912"],
["Manufacture of Products of Wood, Bamboo, Canes, Rattan","2029"],
["Manufacture of Pulp, Paper, Paperboard","2101"],
["Manufacture of Pumps, Compressors, Taps, Valves","2912"],
["Manufacture of Railway, Tramway Locomotives, Rolling Stock","3520"],
["Manufacture of Raincoats Except Rubber Or Plastics","1891"],
["Manufacture of Rattan and Cane Containers","2021"],
["Manufacture of Refined Petroleum Products","2320"],
["Manufacture of Refractory Ceramic Products","2692"],
["Manufacture of Rubber Shoes","1922"],
["Manufacture of Rubber Tires, Tubes","2511"],
["Manufacture of Semi-Conductor Devices","3220"],
["Manufacture of Shoes of Textile Materials W/ Applied Soles","1924"],
["Manufacture of Silverware, Platedware","3912"],
["Manufacture of Snack Products","1564"],
["Manufacture of Soap, Detergent Perfumes and Preparations","2425"],
["Manufacture of Soft Drinks, Bottling of Mineral Waters","1554"],
["Manufacture of Sporting and Athletic Goods, N.E.C","3939"],
["Manufacture of Sporting Balls","3932"],
["Manufacture of Sporting Gloves, Mitts","3931"],
["Manufacture of Starches and Starch Products","1541"],
["Manufacture of Steam Generators","2813"],
["Manufacture of String Instruments, Other Than Guitars","3923"],
["Manufacture of Structural Metal Products","2811"],
["Manufacture of Structural Nonrefractory Clay, Ceramic Prdcts","2693"],
["Manufacture of Sugar, N.E.C","1579"],
["Manufacture of Synthetic Or Artificial Filament Yarns","2431"],
["Manufacture of Tanks, Reservoirs, Containers of Metal","2812"],
["Manufacture of Toys and Games, N.E.C","3949"],
["Manufacture of Tv, Radio Receivers, Recording Apparatus","3240"],
["Manufacture of Tv, Radio Transmitters, Apparatus","3230"],
["Manufacture of Umbrellas, Walking Sticks, Canes, Whips","3993"],
["Manufacture of Vegetable, Animal Oils, Fats","1515"],
["Manufacture of Veneer Sheets, Plywood, Panels, Boards","2012"],
["Manufacture of Watches and Clocks","3330"],
["Manufacture of Weapons and Ammunition","2927"],
["Manufacture of Wheeled Toys","3942"],
["Manufacture of Wind and Percussion Instruments","3924"],
["Manufacture of Wines","1552"],
["Manufacture of Wood Carvings","2014"],
["Manufacture of Wooden Containers","2015"],
["Manufacture of Wooden Footwear and Accessories","1925"],
["Marble Quarrying","1131"],
["Market Research and Public Opinion Polling","7413"],
["Men's, Boy's Garment Manufacturing","1811"],
["Motion Picture Projection","9212"],
["Motion Picture, Video Production, Distribution","9211"],
["Motor Vehicles, Retailing","5012"],
["Motor Vehicles, Wholesaling","5011"],
["Museum Activities, Preservation of Historical Sites","9232"],
["National Postal Activities","6411"],
["News Agency Activities","9220"],
["Nickel Ore Mining","1093"],
["Non-Bank Thrift Institution Operation","6698"],
["Non-Ferrous Metal Casting","2732"],
["Non-Ferrous Rolling, Drawing and Extrusion","2723"],
["Non-Ferrous Smelting, Refining, Except Precious Metals","2722"],
["Non-Life Insurance","6703"],
["Non-Scheduled Air Transport","6220"],
["Ocean Fishing, Commercial (W/ Vessels Over 3 Tons)","0611"],
["Oil and Gas Exploration On Contract Basis","1193"],
["Oil and Gas Extraction Activities On Contract Basis","1192"],
["Operation of Blast Furnaces and Steel Making Furnaces","2711"],
["Operation of Fish Breeding Farms and Nurseries","0643"],
["Operation of Forest Tree Nurseries","0503"],
["Operation of Freight Transport By Road","6013"],
["Operation of Irrigation Systems Through Cooperatives","0311"],
["Operation of Irrigation Systems Through Non-Cooperatives","0312"],
["Operation of Steel Works and Rolling Mills","2712"],
["Other Animal Farming, N.E.C","0299"],
["Other Building Completion Activities","4549"],
["Other Business Activities, N.E.C.","7499"],
["Other Computer Related Activities","7290"],
["Other Credit Granting N.E.C","6619"],
["Other Cultural Activities, N.E.C","9239"],
["Other Entertainment Activities, Dance Instruction","9219"],
["Other Fishing Activities, N.E.C","0699"],
["Other Forestry Activities: Firewood Cutting, Charcoal-Making","0509"],
["Other Hospital Activities, Medical, Dental Practices","8519"],
["Other Land Transport Operation N.E.C","6099"],
["Other Metallic Ore Mining N.E.C","1099"],
["Other Mollusk and Crustacean Farm Operations N.E.C","0659"],
["Other Non-Metallic Mining and Quarrying N.E.C","1199"],
["Other Non-Store Retail Sale","5259"],
["Other Private Education Services, N.E.C.","8159"],
["Other Public Education Services, N.E.C.","8059"],
["Other Publishing","2219"],
["Other Real Estate Activities With Own Or Leased Property","7019"],
["Other Recreational Activities","9249"],
["Other Retail Sale In Specialized Stores","5239"],
["Other Service Activities, N.E.C","9309"],
["Other Short-Stay Accommodation","5519"],
["Other Supporting Land Transport Activities","6319"],
["Other Wholesaling","5190"],
["Oyster and Mussel Farm Operation","0651"],
["Packaging Activities","7495"],
["Painting and Related Work","4541"],
["Pawnshop Operators","6620"],
["Pearl Culture","0661"],
["Pearl Shell Gathering","0662"],
["Pension Funding/Fund Management","6702"],
["Photographic Activities","7494"],
["Pigeon Farming","0244"],
["Planting, Transplanting, Other Related Services","0320"],
["Plowing, Seeding, Weeding, Thinning, Pruning Services","0331"],
["Plumbing and Related Work","4531"],
["Poultry Farming, N.E.C","0249"],
["Prawn Culture","0630"],
["Pre-Need Plan Activities","6814"],
["Preparation and Finishing of Textiles (Integrated)","1713"],
["Preparation, Spinning, Weaving of Textile Fibers","1711"],
["Printing","2221"],
["Private Adult Education","8151"],
["Private Elementary Education For Handicapped Children","8113"],
["Private Elementary Education (Gr I-Vii)","8112"],
["Private General Secondary Education","8121"],
["Private Higher Education, N.E.C.","8149"],
["Private Household With Employed Persons","9500"],
["Private Medical, Dental, Other Health Services","8512"],
["Private Pre-School Education","8111"],
["Private Secondary Education For Handicapped Children","8122"],
["Private Technical and Vocational Secondary Education","8123"],
["Private Tech/Vocational Post-2ndary Non-Degree Education","8130"],
["Processing of Fresh Milk and Cream","1521"],
["Processing, Preserving of Fish/Fish Products/Seafoods","1513"],
["Processing, Preserving of Fruits and Vegetables","1514"],
["Production of Animal Skins From Hunting Activities","0420"],
["Production of Crude Coocnut Oil, Copra Cake, Meals, Pellets","1580"],
["Production of Prepared Animal Feeds","1542"],
["Production, Processing, Preserving of Meat/Meat Products","1512"],
["Public Adult Education","8051"],
["Public Elementary Education For Handicapped Children","8013"],
["Public Elementary Education (Gr I-Vii)","8012"],
["Public Higher Education","8040"],
["Public Medical, Dental, Other Health Services","8511"],
["Public Order, Safety Activities","7523"],
["Public Pre-School Education","8011"],
["Public Secondary Education","8021"],
["Public Secondary Education For Handicapped Children","8022"],
["Public Techl/Vocation Post-2ndary Non-Degree Education","8030"],
["Public Technical and Vocational Secondary Education","8023"],
["Public Utility Cars and Taxicabs Operation","6091"],
["Publishing and Printing Activities","2230"],
["Publishing of Books, Brochures, Musical Books","2211"],
["Publishing of Newspapers, Journals and Periodicals","2212"],
["Publishing of Recorded Media","2213"],
["Quail Egg Production","0253"],
["Quail Farming","0242"],
["Rabbit Farming","0295"],
["Radio, Television Activities","9213"],
["Raising of Semi-Domesticated Or Wild Animals","0297"],
["Ready-Made Embroidered Garments Manufacturing","1813"],
["Real Estate Activities On A Fee Or Contract Basis","7020"],
["Real Estate Buying, Developing, Subdividing, Selling","7012"],
["Rebuilding, Repairing: Machinery, Equipment, Parts","2940"],
["Recycling of Metal Waste, Scrap","3710"],
["Recycling of Non-Metal Waste, Scrap","3720"],
["Refreshment Stands, Kiosks and Counters","5522"],
["Regular Commercial Banking","6592"],
["Regulation Of/ Contribution To Efficient Business Operation","7513"],
["Regulation of The Activities of Social Service Agencies","7512"],
["Rental of Farm Machinery With Drivers, Crews","0350"],
["Renting of Agricultural Machinery and Equipment","7121"],
["Renting of Air Transport Equipment","7113"],
["Renting of Construction, Civil Enginer'g Machinery, Eqpmnt","7122"],
["Renting of Construction, Demolition Equipment W/ Operator","4550"],
["Renting of Land Transport Equipment","7111"],
["Renting of Office Machinery, Equipment","7123"],
["Renting of Other Machinery, Equipment N.E.C","7129"],
["Renting of Personal, Household Goods","7130"],
["Renting of Ship With Operator","6130"],
["Renting of Water Transport Equipment","7112"],
["Reproduction of Recorded Media","2240"],
["Research and Experimental Devt In Agricultural Sciences","7313"],
["Research and Experimental Devt In Engineering, Technology","7312"],
["Research and Experimental Devt In Health Sciences","7314"],
["Research and Experimental Devt In Humanities","7322"],
["Research and Experimental Devt In Information Technology","7330"],
["Research and Experimental Devt In Natural Sciences","7311"],
["Research and Experimental Devt In Social Sciences","7321"],
["Restaurants, Bars, Canteens, Eating and Drinking Places","5529"],
["Restaurants, Cafes and Fastfood Centers","5521"],
["Retail In Non-Specialized Stores (Department Stores)","5219"],
["Retail In Non-Specialized Stores: Food, Beverages, Tobacco","5211"],
["Retail In Specialized Stores: Food, Beverages, Tobacco","5220"],
["Retail of Agricultural Farm Supplies, Equipment","5238"],
["Retail of Books, Office/School Supplies, Newspapers, Mgzns","5235"],
["Retail of Household Applicances, Articles, Equipment","5233"],
["Retail of Liquefied Petroleum Gas, Other Fuel Products","5237"],
["Retail of Office Machines, Equipment, Computers","5236"],
["Retail of Personal and Household Goods","5260"],
["Retail of Pharmaceutical, Medical, Cosmetic, Toilet Articles","5231"],
["Retail of Textiles, Clothing, Footwear, Leather Goods","5232"],
["Retail Sale of Automotive Fuel","5050"],
["Retail Sale of Hardware, Paints and Glass","5234"],
["Retail Sale of Second-Hand Goods In Stores","5240"],
["Retail Sale Via Mail/Telephone Order","5251"],
["Retail Sale Via Stalls and Markets","5252"],
["Rice and Corn Milling","1530"],
["Rural Banking","6594"],
["Sale, Maintenance and Repair of Motorcycles And","5040"],
["Sale of Motor Vehicle Parts and Accessories","5030"],
["Sand and Gravel Quarrying","1135"],
["Sanitary and Similar Services N.E.C","9009"],
["Sawmilling and Planing of Wood","2011"],
["Scheduled Air Transport","6210"],
["Sea and Coastal Water Transport","6110"],
["Seaweeds Farming","0670"],
["Securities Dealership, Own Account","6693"],
["Security Dealing Activities","6812"],
["Sericulture (Silkworm Culture For The Production of Cocoon)","0291"],
["Service Activities Incidental To Fishing","0680"],
["Service Activities Related To Printing","2222"],
["Services To Establish Crops, Promote Their Growth","0339"],
["Services To Promote Propagation, Growth of Animals","0379"],
["Sheep Farming, Sheep Shearing By Owner","0224"],
["Silica Sand and Silica Stone Quarrying","1136"],
["Site Preparation","4510"],
["Slaughtering and Meat Packing","1511"],
["Social Work With Accommodation","8531"],
["Social Work Without Accommodation","8532"],
["Software Consultancy, Supply","7220"],
["Software Development","7230"],
["Specialized Government Banking","6595"],
["Sporting Activities","9241"],
["Steam and Hot Water Supply","4030"],
["Stone Quarrying, Clay and Sand Pits N.E.C","1139"],
["Stone Quarrying, Except Limestone and Marble","1133"],
["Storage and Warehouseing N.E.C","6349"],
["Sugarcane Milling","1571"],
["Sugar Refining","1572"],
["Supporting and Auxiliary Activities To Air Transport","6330"],
["Supporting and Auxiliary Activities To Water Transport","6320"],
["Tanning, Dressing of Leather","1911"],
["Technical Testing, Analysis","7422"],
["Telecommunications","6420"],
["Theological Schools and Seminaries","8141"],
["Thrift Banking","6593"],
["Tobacco Manufacturing, N.E.C","1609"],
["Tourist Assistance Activities (E.G., Tourist Guides), N.E.C","6359"],
["Transport Via Pipelines","6020"],
["Transport Via Railways","6012"],
["Treatment, Coating of Metals, Mechanical Engineering","2892"],
["Tricycles and Pedicabs Operation","6093"],
["Trust and Investment Management Corporation","6696"],
["Turkey Farming","0243"],
["Venture Capital Corporation Operation","6695"],
["Vermiculture","0293"],
["Veterinary Activities","8520"],
["Washing and (Dry-) Cleaning of Clothing and Textile","9301"],
["Waste Collection, Disposal On A Fee/Contractual Basis","9001"],
["Water Well Drilling and Water Pump Installation","4534"],
["Wholesale of Agricultural Raw Materials, Live Animals","5121"],
["Wholesale of Food, Beverages and Tobacco","5122"],
["Wholesale of Hardware, Plumbing, Heating Equipment","5143"],
["Wholesale of Machinery, Equipment and Supplies","5150"],
["Wholesale of Metals and Metal Ores","5142"],
["Wholesale of Other Household Goods","5139"],
["Wholesale of Other Intermediate Products, Waste, Scrap","5149"],
["Wholesale of Solid, Liquid, Gaseous Fuels","5141"],
["Wholesale of Textiles, Clothing, Footwear","5131"],
["Wholesale On A Fee Or Contract Basis","5110"],
["Women's, Girl's, Babies' Garment Manufacturing","1812"]
]
